// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjIT6Zz7KNPyCUL5kjm1qshgUrz1OLLsM',
    appId: '1:463762864980:web:0b7eec447ce9ecf663e6c1',
    messagingSenderId: '463762864980',
    projectId: 'gontran-52c4b',
    authDomain: 'gontran-52c4b.firebaseapp.com',
    storageBucket: 'gontran-52c4b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGYH2nIDx6YOzAXIgqgWtmuzL74B4XNBs',
    appId: '1:463762864980:android:28a950d20e40dd0f63e6c1',
    messagingSenderId: '463762864980',
    projectId: 'gontran-52c4b',
    storageBucket: 'gontran-52c4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcjTxjsj7iRVSVA73V5e0H8KqAU_MOGSE',
    appId: '1:463762864980:ios:2af3c949b665ec9e63e6c1',
    messagingSenderId: '463762864980',
    projectId: 'gontran-52c4b',
    storageBucket: 'gontran-52c4b.firebasestorage.app',
    iosBundleId: 'com.monprojet.gontran',
  );
}
